services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: api
  #   container_name: api-container
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   command: >
  #     bash -c "sleep 5 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"


volumes:
  postgres_data: {}